export const elements = {
  body: document.querySelector('body'),
  menu: document.querySelectorAll('.menu-icon'),
  notify: document.querySelector('#notify'),
  canvas: document.querySelector('#off-canvas'),
  canvasFooter: document.querySelector('#off-canvas-footer'),
  noGpView: document.querySelector('#no-gp-yet'),
  noGpViewImg: document.querySelector('#no-gp-yet div img'),
  noGpViewP: document.querySelector('#no-gp-yet div p'),
  modePop: document.querySelector('#mode-popup'),
  proceedBtn: document.querySelector('#proceed-btn'),
  showCalcArea: document.querySelector('#showCalcArea'),
  calcAreaUni: document.querySelector('#calcAreaUni') ,
  calcAreaPoly: document.querySelector('#calcAreaPoly') ,
  addGpRowBtn: document.querySelectorAll('.addGpRow'),
  gpCalcUl: document.querySelector('#gpCalcUl'),
  gpDisplayInput: document.querySelector('#gpa-display #gpaId'),
  gpDisplayMode: document.querySelector('#gpa-display #gpaMode'),
  gpDisplay: document.querySelector('#gpa-display h1'),
  gpDisplayP: document.querySelector('#gpa-display p'),
  showSaveGpPopBtn: document.querySelectorAll('.saveGpBtn'),
  savePopup: document.querySelector('#save-popup'),
  savePopupP: document.querySelector('#save-popup p'),
  saveGp: document.querySelector('#save-btn'),
  gpNameInput: document.querySelector('#gpName'),
  showSavedGp: document.querySelector('#show-saved-gp'),
  showSavedGpBtn: document.querySelector('#showSavedGpBtn'),
  gpShowUl: document.querySelector('#gpShowUl'),
  showCalcAreaBtn: document.querySelector('#showCalcAreaBtn'),
  closePop: document.querySelectorAll('.close-pop'),
  searchInput: document.querySelector('#search'),
  editAreaUni: document.querySelector('#editAreaUni'),
  editAreaPoly: document.querySelector('#editAreaPoly'),
  gpEditUlUni: document.querySelector('#gpEditUlUni'),
  gpEditUlPoly: document.querySelector('#gpEditUlPoly'),
  addGpRowEdit: document.querySelectorAll('.addGpRowEdit'),
  showUpdateGpPopBtn: document.querySelectorAll('.updateGpBtn'),
  updatePopup: document.querySelector('#update-popup'),
  updatePopupP: document.querySelector('#update-popup p'),
  gpEditNameInput: document.querySelector('#gpEditName'),
  updateGp: document.querySelector('#update-btn'),
  gpCalcUlPoly: document.querySelector('#gpCalcUlPoly'),
  footerDiv: document.querySelectorAll('.addField-container'),
  aboutSec: document.querySelector('#about'),
  aboutBtn: document.querySelector('#about_btn'),
  overlay: document.querySelector('#overlay'),
  closeMenu: document.querySelector('#close-menu'),
  allPopups: document.querySelectorAll('#save-popup, #update-popup, #mode-popup')
}